#!/usr/bin/env python

from decimal import Decimal

NOMBRE_INSTITUCION = 'GM SOFT'
IVA = Decimal('0.07')

# VARIABLE PARA LOS TIPOS DE PRODUCTOS FAVORITOS
TIPO_PRODUCTOS_FAVORITOS_ID = 9

# VARIABLE PARA IMPORTACION DE INGRESOS EN CAJA
FACTURACION_API_URL = "http://localhost/api"

# IPs configuradas para trabajar localmente
ALLOWED_IPS_FOR_INHOUSE = ['*']

# ACCIONES PARA TABLAS AUDITORIAS
ACCION_ADICIONAR = 'A'
ACCION_MODIFICAR = 'M'
ACCION_ELIMINAR = 'E'
